# .goreleaser.yml
project_name: file-utils
builds:
  - env: [CGO_ENABLED=0]
    binary: ./bin/file-utils
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: "file-utils"
    dir: .
    main: ./cmd
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - plugin.yaml
      - README.md
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"