# .goreleaser.yml
project_name: helm-file-utils
builds:
  - env: [CGO_ENABLED=0]
    binary: ./bin/helm-file-utils
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: "helm-file-utils"
    dir: .
    main: ./cmd
archive:
  format: tar.gz
  files:
#    - LICENSE
    - plugin.yaml