name: "file-utils"
version: "0.1.3"
usage: "File conversions, encoding and decoding utility protocols"
description: "File conversions, encoding and decoding utility protocols"
command: "$HELM_PLUGIN_DIR/bin/file-utils"
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; ./scripts/install_plugin.sh"
downloaders:
  - command: "bin/file-utils"
    protocols:
      - "futl"
