name: "file-utils"
version: "v0.0.1"
usage: "File conversions, encoding and decoding utility protocols"
description: "File conversions, encoding and decoding utility protocols"
command: "$HELM_PLUGIN_DIR/bin/file-utils"
downloaders:
  - command: "bin/file-utils"
    protocols:
      - "base64enc"
      - "futl"
      - "file"
